### ISSUE TITLE
Automating version release process

### ISSUE THREAD

**Issue by jackmoody11** [coyo8/sec-edgar#66]
**Is your feature request related to a problem? Please describe.**
There is not a clearly defined system to release new versions. It would be nice to have some sort of versioneer, like the [one used in the pandas project](https://github.com/pandas-dev/pandas/blob/master/versioneer.py), to automate this process.

**Describe the solution you'd like**
A script to automate versioning and simplify releases.

**Comment by jackmoody11** [comment]
@coyo8 did you add your username/password for PyPi when you added the GitHub action to send to PyPi on version release? The code looks like this.

```yaml
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
```

If not, here is [a how-to guide](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets) for storing encrypted values on GitHub.
